simulation:
    ros__parameters:

        hz: 20.0

        map:
            seed: 26
            width: 20.0
            height: 20.0
            obstacles: 26
            resolution: 0.05
            name: "world"

        target:
            x: -7.0
            y: 0.0
            yaw: 0.0
            radius: 0.1
            name: "target"
            
            # For planning
            max_vel: 1.5
            max_acc: 1.0

        tracker:
            x: -9.5
            y: 0.0
            yaw: 0.0
            fps: 10.0
            fov: 135.0
            range: 6.0
            radius: 0.1
            name: "tracker"
